name: Minecraft Stats Tracker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
  workflow_dispatch: # Allows manual testing

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
      - run: node ping.js ${{ secrets.SERVER_TYPE }} ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_PORT }}

      - name: Bot Details
        id: bot-details
        uses: raven-actions/bot-details@v1

      - name: Commit & push
        run: |
          git config --global user.name "${{ steps.bot-details.outputs.name }}"
          git config --global user.email "${{ steps.bot-details.outputs.email }}"
          git add stats.json
          git commit -m "[ bot ] Update server stats"
          git push origin
